### ISSUE TITLE
Drag things from pending to Started?

### ISSUE THREAD

**Issue by jpaugh** [jamesandrews23/Personal_Task_Manager#1]
The first thing I wanted to do was drag a task into the started state. I wonder how easily it can be done?

Here's a [reference][1].

[1]: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#The_basics

**Comment by jamesandrews23** [comment]
Well it wasn't easy, but I did it. You can now drag and drop tasks from one column to the next.
